<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>分散分析 | マーケティング・データ分析補足資料</title>
  <meta name="description" content="分散分析 | マーケティング・データ分析補足資料" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="分散分析 | マーケティング・データ分析補足資料" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="https://github.com/tak-tag/mktg_analysis_comp.github.io" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="分散分析 | マーケティング・データ分析補足資料" />
  
  
  



<meta name="date" content="2025-11-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="meancomparison.html"/>
<link rel="next" href="pwr.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>本ウェブサイトについて</a></li>
<li class="chapter" data-level="" data-path="rusage.html"><a href="rusage.html"><i class="fa fa-check"></i>R と R studioに慣れる</a>
<ul>
<li class="chapter" data-level="" data-path="ch2intro.html"><a href="ch2intro.html"><i class="fa fa-check"></i>本章の概要</a></li>
<li class="chapter" data-level="" data-path="desktop.html"><a href="desktop.html"><i class="fa fa-check"></i>R studio デスクトップ版の利用</a></li>
<li class="chapter" data-level="" data-path="project.html"><a href="project.html"><i class="fa fa-check"></i>プロジェクト機能について</a></li>
<li class="chapter" data-level="" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i>Rの基本操作</a></li>
<li class="chapter" data-level="" data-path="rscript.html"><a href="rscript.html"><i class="fa fa-check"></i>R スクリプトのすゝめ</a>
<ul>
<li class="chapter" data-level="" data-path="rscript.html"><a href="rscript.html#writeRscript"><i class="fa fa-check"></i>Rスクリプトを書く</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch2summary.html"><a href="ch2summary.html"><i class="fa fa-check"></i>本章のまとめ</a></li>
<li class="chapter" data-level="" data-path="positcloud.html"><a href="positcloud.html"><i class="fa fa-check"></i>コラム：Posit cloudを使ってみる</a></li>
<li class="chapter" data-level="" data-path="ch2reference.html"><a href="ch2reference.html"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="handling.html"><a href="handling.html"><i class="fa fa-check"></i>データ整理と要約・可視化</a>
<ul>
<li class="chapter" data-level="" data-path="Ch3intro.html"><a href="Ch3intro.html"><i class="fa fa-check"></i>本章の概要</a></li>
<li class="chapter" data-level="" data-path="readData.html"><a href="readData.html"><i class="fa fa-check"></i>データの読み込み</a></li>
<li class="chapter" data-level="" data-path="normalization.html"><a href="normalization.html"><i class="fa fa-check"></i>データの整形</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#tidyverse-%E3%81%AE%E6%B4%BB%E7%94%A8"><i class="fa fa-check"></i>tidyverse の活用</a></li>
<li class="chapter" data-level="" data-path="normalization.html"><a href="normalization.html#firmdata"><i class="fa fa-check"></i>企業データの処理</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i>データの要約と可視化</a>
<ul>
<li class="chapter" data-level="" data-path="summary.html"><a href="summary.html#descriptiveStat"><i class="fa fa-check"></i>記述統計</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="categoricalVar.html"><a href="categoricalVar.html"><i class="fa fa-check"></i>カテゴリ変数の要約</a></li>
<li class="chapter" data-level="" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i>データの可視化</a></li>
<li class="chapter" data-level="" data-path="cor.html"><a href="cor.html"><i class="fa fa-check"></i>二変数間の関係の要約</a></li>
<li class="chapter" data-level="" data-path="ch3reference.html"><a href="ch3reference.html"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="test.html"><a href="test.html"><i class="fa fa-check"></i>基礎統計学復習</a>
<ul>
<li class="chapter" data-level="" data-path="ch4Intro.html"><a href="ch4Intro.html"><i class="fa fa-check"></i>本章の概要</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i>確率モデル、期待値と分散</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#discrete"><i class="fa fa-check"></i>確率と離散確率変数</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#continuous"><i class="fa fa-check"></i>連続確率変数</a></li>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#expectation"><i class="fa fa-check"></i>期待値</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i>統計的推測</a></li>
<li class="chapter" data-level="" data-path="pestimate.html"><a href="pestimate.html"><i class="fa fa-check"></i>点推定</a></li>
<li class="chapter" data-level="" data-path="estimates.html"><a href="estimates.html"><i class="fa fa-check"></i>推定量もまた確率変数</a></li>
<li class="chapter" data-level="" data-path="distribution.html"><a href="distribution.html"><i class="fa fa-check"></i>補足（いくつかの確率分布の関係性）</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#%E6%AD%A3%E8%A6%8F%E5%88%86%E5%B8%83"><i class="fa fa-check"></i>正規分布</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E3%82%AB%E3%82%A4%E4%BA%8C%E4%B9%97%E5%88%86%E5%B8%83"><i class="fa fa-check"></i>カイ二乗分布</a></li>
<li class="chapter" data-level="" data-path=""><a href="#t%E5%88%86%E5%B8%83"><i class="fa fa-check"></i>t分布</a></li>
<li class="chapter" data-level="" data-path=""><a href="#f%E5%88%86%E5%B8%83"><i class="fa fa-check"></i>F分布</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intinf.html"><a href="intinf.html"><i class="fa fa-check"></i>区間推定</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#%E6%A8%99%E6%BA%96%E6%AD%A3%E8%A6%8F%E5%88%86%E5%B8%83%E3%81%AB%E5%9F%BA%E3%81%A5%E3%81%8F%E4%BF%A1%E9%A0%BC%E5%8C%BA%E9%96%93%E3%81%AE%E6%B1%82%E3%82%81%E6%96%B9"><i class="fa fa-check"></i>標準正規分布に基づく信頼区間の求め方*</a></li>
<li class="chapter" data-level="" data-path=""><a href="#t%E5%88%86%E5%B8%83%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E5%8C%BA%E9%96%93%E6%8E%A8%E5%AE%9A"><i class="fa fa-check"></i>t分布を使った区間推定*</a></li>
<li class="chapter" data-level="" data-path="intinf.html"><a href="intinf.html#infwithR"><i class="fa fa-check"></i>Rによる区間推定</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="testtheory.html"><a href="testtheory.html"><i class="fa fa-check"></i>統計的仮説検定</a>
<ul>
<li class="chapter" data-level="" data-path="testtheory.html"><a href="testtheory.html#nullhypo"><i class="fa fa-check"></i>検定の手順と仮説</a></li>
<li class="chapter" data-level="" data-path="testtheory.html"><a href="testtheory.html#twotail"><i class="fa fa-check"></i>母平均の検定（両側検定）に関する理屈</a></li>
<li class="chapter" data-level="" data-path="testtheory.html"><a href="testtheory.html#onetail"><i class="fa fa-check"></i>片側検定の紹介</a></li>
<li class="chapter" data-level="" data-path="testtheory.html"><a href="testtheory.html#errors"><i class="fa fa-check"></i>有意水準と検定における誤り</a></li>
<li class="chapter" data-level="" data-path="testtheory.html"><a href="testtheory.html#testresults"><i class="fa fa-check"></i>検定結果に関する解釈</a></li>
<li class="chapter" data-level="" data-path="testtheory.html"><a href="testtheory.html#lightbulb"><i class="fa fa-check"></i>電球データと検定</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="meancomparison.html"><a href="meancomparison.html"><i class="fa fa-check"></i>平均値に関するその他の検定</a></li>
<li class="chapter" data-level="" data-path="ANOVA.html"><a href="ANOVA.html"><i class="fa fa-check"></i>分散分析</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#%E5%88%86%E6%95%A3%E5%88%86%E6%9E%90%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%81%AE%E3%83%A2%E3%83%87%E3%83%AB%E8%A1%A8%E7%8F%BEanoatheory"><i class="fa fa-check"></i>分散分析についてのモデル表現*{#ANOAtheory}</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E4%BA%8C%E5%85%83%E9%85%8D%E7%BD%AE%E5%88%86%E6%95%A3%E5%88%86%E6%9E%90twowayanoa"><i class="fa fa-check"></i>二元配置分散分析*{#twowayANOA}</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E4%BA%8C%E5%85%83%E9%85%8D%E7%BD%AE%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E5%8A%B9%E6%9E%9C%E6%A4%9C%E5%AE%9Atwowaytest"><i class="fa fa-check"></i>二元配置モデルの効果検定*{#twowaytest}</a></li>
<li class="chapter" data-level="" data-path="ANOVA.html"><a href="ANOVA.html#tukey"><i class="fa fa-check"></i>多重比較とそれに伴う統計的問題</a></li>
<li class="chapter" data-level="" data-path="ANOVA.html"><a href="ANOVA.html#ANOVAwithR"><i class="fa fa-check"></i>Rによる分散分析の実行</a></li>
<li class="chapter" data-level="" data-path="ANOVA.html"><a href="ANOVA.html#ANOVAandReg"><i class="fa fa-check"></i>回帰分析と分散分析の関係</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="pwr.html"><a href="pwr.html"><i class="fa fa-check"></i>検定力分析とサンプルサイズ</a></li>
<li class="chapter" data-level="" data-path="ch4reference.html"><a href="ch4reference.html"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regintro.html"><a href="regintro.html"><i class="fa fa-check"></i>回帰分析</a>
<ul>
<li class="chapter" data-level="" data-path="ch5Intro.html"><a href="ch5Intro.html"><i class="fa fa-check"></i>本章の概要</a></li>
<li class="chapter" data-level="" data-path="regpreparation.html"><a href="regpreparation.html"><i class="fa fa-check"></i>分析準備</a></li>
<li class="chapter" data-level="" data-path="prediction.html"><a href="prediction.html"><i class="fa fa-check"></i>単回帰モデルと予測値</a>
<ul>
<li class="chapter" data-level="" data-path="prediction.html"><a href="prediction.html#lmmodel"><i class="fa fa-check"></i>企業データを用いた回帰分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multiplereg.html"><a href="multiplereg.html"><i class="fa fa-check"></i>重回帰モデル</a>
<ul>
<li class="chapter" data-level="" data-path="multiplereg.html"><a href="multiplereg.html#mregIntro"><i class="fa fa-check"></i>重回帰モデル概要</a></li>
<li class="chapter" data-level="" data-path="multiplereg.html"><a href="multiplereg.html#mreginterpret"><i class="fa fa-check"></i>回帰係数の解釈</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="modelcomp.html"><a href="modelcomp.html"><i class="fa fa-check"></i>単回帰モデルと重回帰モデルの比較</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regtechnic.html"><a href="regtechnic.html"><i class="fa fa-check"></i>回帰分析上の工夫紹介</a>
<ul>
<li class="chapter" data-level="" data-path="ch6Intro.html"><a href="ch6Intro.html"><i class="fa fa-check"></i>本章の概要</a></li>
<li class="chapter" data-level="" data-path="dummy.html"><a href="dummy.html"><i class="fa fa-check"></i>ダミー変数</a>
<ul>
<li class="chapter" data-level="" data-path="dummy.html"><a href="dummy.html#dummywithR"><i class="fa fa-check"></i>企業データを用いた分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="interaction.html"><a href="interaction.html"><i class="fa fa-check"></i>交差項</a>
<ul>
<li class="chapter" data-level="" data-path="interaction.html"><a href="interaction.html#slopedummy"><i class="fa fa-check"></i>傾きダミー</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E5%82%BE%E3%81%8D%E3%83%80%E3%83%9F%E3%83%BC%E3%81%AE%E5%AE%9F%E8%A1%8Cslopedummywithr"><i class="fa fa-check"></i>傾きダミーの実行{slopedummywithR}</a></li>
<li class="chapter" data-level="" data-path="interaction.html"><a href="interaction.html#id_5"><i class="fa fa-check"></i>量的変数同士の交差項</a></li>
<li class="chapter" data-level="" data-path="interaction.html"><a href="interaction.html#interactionwithR"><i class="fa fa-check"></i>交差項モデルの実行</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="coefComparison.html"><a href="coefComparison.html"><i class="fa fa-check"></i>係数比較</a>
<ul>
<li class="chapter" data-level="" data-path="coefComparison.html"><a href="coefComparison.html#coefComparisonwithR"><i class="fa fa-check"></i>係数比較の実行</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logLinearModel.html"><a href="logLinearModel.html"><i class="fa fa-check"></i>対数線形</a>
<ul>
<li class="chapter" data-level="" data-path="logLinearModel.html"><a href="logLinearModel.html#logLinearwithR"><i class="fa fa-check"></i>対数線形モデルの分析実行</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E9%9C%80%E8%A6%81%E3%81%AE%E4%BE%A1%E6%A0%BC%E5%BC%BE%E5%8A%9B%E6%80%A7%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6elasticity"><i class="fa fa-check"></i>需要の価格弾力性について*{#elasticity}</a></li>
<li class="chapter" data-level="" data-path="logLinearModel.html"><a href="logLinearModel.html#linearTest"><i class="fa fa-check"></i>対数線形の推定と検定</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ch6Reference.html"><a href="ch6Reference.html"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="choice.html"><a href="choice.html"><i class="fa fa-check"></i>消費者の選択と離散選択モデル</a>
<ul>
<li class="chapter" data-level="" data-path="Ch7Intro.html"><a href="Ch7Intro.html"><i class="fa fa-check"></i>本章の概要</a></li>
<li class="chapter" data-level="" data-path="discretechoice.html"><a href="discretechoice.html"><i class="fa fa-check"></i>離散選択モデル</a>
<ul>
<li class="chapter" data-level="" data-path="discretechoice.html"><a href="discretechoice.html#lpm"><i class="fa fa-check"></i>線形確率モデル</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E3%83%97%E3%83%AD%E3%83%93%E3%83%83%E3%83%88%E3%83%A2%E3%83%87%E3%83%AB%E3%81%A8%E3%83%AD%E3%82%B8%E3%83%83%E3%83%88%E3%83%A2%E3%83%87%E3%83%ABlogitprobit"><i class="fa fa-check"></i>プロビットモデルとロジットモデル*{#logitprobit}</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E6%BD%9C%E5%9C%A8%E5%A4%89%E6%95%B0%E3%82%A2%E3%83%97%E3%83%AD%E3%83%BC%E3%83%81%E3%81%AB%E3%82%88%E3%82%8B%E8%AA%AC%E6%98%8Elatentapproach"><i class="fa fa-check"></i>潜在変数アプローチによる説明*{#latentApproach}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="probitwithR.html"><a href="probitwithR.html"><i class="fa fa-check"></i>プロビットモデルの推定と解釈</a>
<ul>
<li class="chapter" data-level="" data-path="probitwithR.html"><a href="probitwithR.html#probitSummary"><i class="fa fa-check"></i>分析の実行と結果のまとめ</a></li>
<li class="chapter" data-level="" data-path="probitwithR.html"><a href="probitwithR.html#marginaleffectwithR"><i class="fa fa-check"></i>限界効果の計算</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%E9%99%90%E7%95%8C%E5%8A%B9%E6%9E%9C%E3%81%8C%E3%81%AA%E3%81%9C%E5%BF%85%E8%A6%81%E3%81%8Bwhymarginal"><i class="fa fa-check"></i>限界効果がなぜ必要か？*{#whymarginal}</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ml.html"><a href="ml.html"><i class="fa fa-check"></i>補足：最尤推定法の紹介</a></li>
<li class="chapter" data-level="" data-path="Mcfadden.html"><a href="Mcfadden.html"><i class="fa fa-check"></i>離散選択モデルへの合理的消費者像の応用</a></li>
<li class="chapter" data-level="" data-path="mlogit.html"><a href="mlogit.html"><i class="fa fa-check"></i>多項選択モデル紹介</a></li>
<li class="chapter" data-level="" data-path="choiceAndPrediction.html"><a href="choiceAndPrediction.html"><i class="fa fa-check"></i>需要の予測と本章のまとめ</a></li>
<li class="chapter" data-level="" data-path="Ch7Reference.html"><a href="Ch7Reference.html"><i class="fa fa-check"></i>参考文献</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">マーケティング・データ分析補足資料</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ANOVA" class="section level2 hasAnchor">
<h2>分散分析<a href="ANOVA.html#ANOVA" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>ここまでの内容では、２グループ間の平均の差に関する分析を捉えた。しかしながら、三つ以上のグループ間の平均の差に関心があることもある。例えば、異なる地域における売上高の差を比較したい場合が挙げられる。このような目的を持つ場合によく用いられるのが分散分析（Analysis of Variance; ANOVA）である。</p>
<p>ANOVAの構造については、要因と水準という二つの要素から説明が行われる。要因とは、観測値に影響を与えていると考えうるカテゴリ変数のことを指し、水準とは、要因を構成するいくつかの条件やグループを指す。例えばある小売企業における各店舗の一定期間内の売上高が出店エリア特性によって差があるのかという問いに関心があるとする。その際各店舗を、都市エリア、郊外エリア、農村エリアという三つのグループに分類し、それぞれのグループにおける標本平均を求めれば、エリアごとの差を分析できるだろう。この場合、「地域」が売上高に影響を与えうる要因であり、「都市、郊外、農村」という三つのグループが水準だと言える。</p>
<p>分析において取り上げる要因が一つである分散分析を一元配置分散分析と呼ぶ。二元配置分散分析については以下の節でモデル表現と共に紹介している。</p>
<div id="分散分析についてのモデル表現anoatheory" class="section level3 hasAnchor">
<h3>分散分析についてのモデル表現*{#ANOAtheory}<a href="#%E5%88%86%E6%95%A3%E5%88%86%E6%9E%90%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%81%AE%E3%83%A2%E3%83%87%E3%83%AB%E8%A1%A8%E7%8F%BEanoatheory" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>本節では、分散分析の構造をモデルによって表現することでより明確な理解を促すことを目指す
。ここでは、要因をA、グループ（水準）の数をJとする。第<span class="math inline">\(j\)</span>グループで<span class="math inline">\(n_j\)</span>個の観測値が得られる。第<span class="math inline">\(j\)</span>水準における<span class="math inline">\(i\)</span>番目の個体の観測値を<span class="math inline">\(y_{ij}\)</span>と表し、以下が成り立つとする。
<span class="math display">\[
y_{ij}=\mu_j+e_{ij},~~~~e_{ij} \sim N(0,\sigma^2),
\]</span></p>
<p>ただし、<span class="math inline">\(i=1,2,...,n_j\)</span>; <span class="math inline">\(j=1,2,...,J\)</span>であるとする。
すべての<span class="math inline">\(y_{ij}\)</span>は独立であり、
<span class="math display">\[
y_{ij}\sim N(\mu_j, \sigma^2)
\]</span>
が成り立つ。したがって、<span class="math inline">\(E(y_{ij})=\mu_j\)</span>と、<span class="math inline">\(V(y_{ij}=\sigma^2)\)</span>も成り立つ。</p>
<p>上記モデルの関心は各グループで平均に差が存在するか否かである。そこで、以下の<span class="math inline">\(\mu\)</span>を全体平均とする。
<span class="math display">\[
\mu=\frac{n_1}{n}\mu_1+\frac{n_2}{n}\mu_2+...+\frac{n_J}{n}\mu_J=\frac{1}{n}\sum^J_{j=1}n_j\mu_j.
\]</span></p>
<p>また、
<span class="math inline">\(\alpha_j=\mu_j-\mu\)</span>を第 <span class="math inline">\(j\)</span>グループの効果と呼び、以下のように表現できる。
<span class="math display">\[
y_{ij}=\mu+\alpha_j+e_{ij} ,
\]</span>
このとき定義より、
<span class="math display">\[
\frac{1}{n}\sum^J_{j=1}n_j\alpha_j=0,
\]</span>が成り立つ。もし、<span class="math inline">\(\alpha_1=\alpha_2=...=\alpha_J=0\)</span>ならば、以下のような水準間の差が存在しないモデルとなる
<span class="math display">\[
y_{ij}=\mu+e_{ij},
\]</span></p>
<p>分散分析の第一の目的は、要因が観測値に対して影響を与えているかどうか、すなわち、<span class="math inline">\(\mu_1=\mu_2=...=\mu_J\)</span>が成立しているかどうかを調べることである。これは全てのグループで主効果<span class="math inline">\(\alpha_j\)</span>がゼロであるかどうかを調べることに等しい。そのため、以下を検定することと等しい。</p>
<p><span class="math display">\[
\begin{cases}
|t|&gt;t_{\alpha/2}(n-2) &amp; \Rightarrow \text{H0を棄却する。}\\
|t|\leq t_{\alpha/2}(n-2)&amp; \Rightarrow \text{H0を採択する。}
\end{cases}
\]</span></p>
<p><span class="math display">\[
\begin{cases}
H_0:~ &amp;\alpha_1=\alpha_2=...=\alpha_J=0\\
H_1:~ &amp;\text{少なくとも１つの}\alpha_j \text{は0ではない}
\end{cases}
\]</span></p>
<p>ここで、総変動: <span class="math inline">\(S_T=\sum^J_{j=1}\sum^{n_j}_{i=1}(y_{ij}-\bar{y})^2\)</span>を、群間変動: <span class="math inline">\(S_B=\sum^J_{j=1}n_j(\bar{y_j}-\bar{y})^2\)</span>と、郡内変動: <span class="math inline">\(S_W=\sum^J_{j=1}\sum^{n_j}_{i=1}(y_{ij}-\bar{y_j})^2\)</span>とに分ける(ただし、<span class="math inline">\(S_T=S_B+S_W\)</span>)。このとき、群間変動が大きいほど各<span class="math inline">\(\alpha\)</span>の推定値<span class="math inline">\(\hat{\alpha_j}=\bar{y_j}-\bar{y}\)</span>のばらつき、すなわちグループ間での平均の違いが大きく、対立仮説<span class="math inline">\(H_1\)</span>が支持されやすい。</p>
<p>しかしながら、この値自体は単位に依存し意味が無いため、以下の群間変動の郡内変動に対する比に基づいて検定を行う。
<span class="math display">\[
F=\frac{S_B/(J-1)}{S_W/(n-J)}=\frac{n-J}{J-1}\times \frac{S_B}{S_W}
\]</span></p>
<p>Fは帰無仮説が正しい時に自由度（<span class="math inline">\(J-1\)</span>, <span class="math inline">\(n-J\)</span>）のF分布に従うことが知られている。そのため、有意水準 <span class="math inline">\(\alpha\)</span> に基づく<span class="math inline">\(H_0\)</span>に関する検定は、以下のように表すことができる。</p>
<p><span class="math display">\[
\begin{cases}
F&gt;F_\alpha(J-1, n-J)\Rightarrow H_0\text{を棄却}\\
F\leq F_\alpha(J-1, n-J)\Rightarrow H_0\text{を採択}
\end{cases}
\]</span></p>
</div>
<div id="二元配置分散分析twowayanoa" class="section level3 hasAnchor">
<h3>二元配置分散分析*{#twowayANOA}<a href="#%E4%BA%8C%E5%85%83%E9%85%8D%E7%BD%AE%E5%88%86%E6%95%A3%E5%88%86%E6%9E%90twowayanoa" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>一元配置分散分析観測値に影響を与える要因が2個あるモデルを考える。この場合の最も特徴的な違いが交互作用効果である。2つの要因をAとBとし、Aのグループの数をJ、Bのグループの数をKとする。（<span class="math inline">\(A_j\)</span>, <span class="math inline">\(B_k\)</span>）につきr個の観測値<span class="math inline">\(y_{ijk}\)</span>（<span class="math inline">\(i=1,2,...,r\)</span>）が得られるとし、以下のモデルを考える。
<span class="math display">\[
y_{ijk}=\mu_{jk}+e_{ijk}, ~e_{ijk}\sim N(0,\sigma^2)
\]</span>
ただし、<span class="math inline">\(i=1,2,...,r\)</span>; <span class="math inline">\(j=1,2,...,J\)</span>; <span class="math inline">\(k=1,2,...,K\)</span>。</p>
<p>前節の内容と同様に全体平均と要因効果とに分解し、全体平均と呼ぶ。
<span class="math display">\[
\mu=\frac{1}{JK}\sum^J_{j=1}\sum^K_{k=1}=\mu_{jk},
\]</span>
そして、全体平均を以下のように分解し、前者を行平均、後者を列平均と呼ぶ。
<span class="math display">\[\begin{eqnarray}
\mu_{j.}=\frac{1}{K}\sum^K_{k=1}=\mu_{jk}, ~~ \mu_{.k}=\frac{1}{J}\sum^J_{j=1}=\mu_{jk},
\end{eqnarray}\]</span></p>
<p>このとき、要因Aの第<span class="math inline">\(j\)</span>グループの効果（<span class="math inline">\(\alpha_j\)</span>）、要因Bの第<span class="math inline">\(k\)</span>グループの効果（<span class="math inline">\(\beta_k\)</span>）をそれぞれ、以下のように定義する。
<span class="math display">\[
\alpha_j=\mu_{j.}-\mu, ~~\beta_k=\mu_{.k}-\mu
\]</span>
この時、以下の恒等式が成り立つ。
<span class="math display">\[
\mu_jk=\mu+(\mu_{j.}-\mu)+(\mu_{.k}-\mu)+(\mu_{jk}-\mu_{j.}-\mu_{.k}-\mu)\nonumber\\
=\mu+\alpha_j+\beta_k+(\alpha \beta)_{jk},
\]</span>
ただし、効果<span class="math inline">\(\alpha_j\)</span>, <span class="math inline">\(\beta_k\)</span>を要因AとBの主効果、<span class="math inline">\((\alpha \beta)_{jk}\)</span>をABの交互作用効果と呼ぶ。そして、定義より以下を示すことができる。
<span class="math display">\[
\sum^J_{j=1}\alpha_j=0, ~~\sum^K_{k=1}\beta_k=0, ~~\sum^J_{j=1}(\alpha \beta)_{jk}=0, ~~ \sum^K_{k=1}(\alpha \beta)_{jk}=0
\]</span>
なお、交互作用効果が無いモデルは、以下のように示すことができる。
<span class="math display">\[\begin{eqnarray}
\mu_{jk}=\mu+\alpha_j+\beta_k
\end{eqnarray}\]</span></p>
</div>
<div id="二元配置モデルの効果検定twowaytest" class="section level3 hasAnchor">
<h3>二元配置モデルの効果検定*{#twowaytest}<a href="#%E4%BA%8C%E5%85%83%E9%85%8D%E7%BD%AE%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E5%8A%B9%E6%9E%9C%E6%A4%9C%E5%AE%9Atwowaytest" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>二元配置モデルにおいても、以下のような要因Aの主効果に関する仮説に関心がある。
<span class="math display">\[
\begin{cases}
H_0:~ \alpha_1=\alpha_2=...=\alpha_J=0\\
H_1:~ \text{少なくとも１つの}\alpha_jは0\text{ではない}
\end{cases}
\]</span></p>
<p>また、要因Bの主効果に関する仮説は以下のように定義できる。
<span class="math display">\[
\begin{cases}
H_0:~ \beta_1=\beta_2=...=\beta_K=0\\
H_1:~ \text{少なくとも１つの}\beta_kは0\text{ではない}
\end{cases}
\]</span></p>
<p>これらに加え、交互作用効果に関する仮説は以下のように示すことができる。</p>
<p><span class="math display">\[
\begin{cases}
H_0:~ (\alpha \beta)_{11}=(\alpha \beta)_{12}=...=(\alpha \beta)_{JK}=0\\
H_1:~ \text{少なくとも１つの}(\alpha \beta)_{jk}\text{ではない}
\end{cases}
\]</span></p>
<p>これらの仮説の検定ではまず、以下のように「総変動」、「A間変動」、「B間変動」、「交互作用変動」、「グループ内変動」を定義する。ただし以下では、<span class="math inline">\(S_T=S_A+S_B+S_{AB}+S_W\)</span> とする。
<span class="math display">\[
\text{総変動:} S_T=\sum^r_{i=1}\sum^J_{j=1}\sum^K_{k=1}=(y_{ijk}-\bar{y})^2
\]</span>
<span class="math display">\[
\text{A間変動:} ~S_A=Kr\sum^J_{j=1}(\bar{y_{j.}}-\bar{y})^2
\]</span>
<span class="math display">\[
\text{B間変動:}~S_B=Jr\sum^K_{k=1}(\bar{y_{.k}}-\bar{y})^2
\]</span>
<span class="math display">\[
\text{交互作用変動:}~S_{AB}=r\sum^K_{k=1}\sum^J_{j=1}(\bar{y_{jk}}-\bar{y_{j.}}-\bar{y_{.k}}-\bar{y})^2
\]</span>
<span class="math display">\[
\text{グループ内変動:}~S_W=\sum^r_{i=1}\sum^K_{k=1}\sum^J_{j=1}(y_{ijk}-\bar{y_{jk}})^2
\]</span></p>
<p>これらを用いて、以下のような <span class="math inline">\(F_A\)</span>、<span class="math inline">\(F_B\)</span>、<span class="math inline">\(F_{AB}\)</span> を検定統計量として検定を行う。
<span class="math display">\[
F_A=\frac{S_A/(J-1)}{S_W/JK(r-1)}
\]</span>
<span class="math display">\[
F_B=\frac{S_B/(K-1)}{S_W/JK(r-1)}
\]</span>
<span class="math display">\[
F_{AB}=\frac{S_{AB}/(J-1)(K-1)}{S_W/JK(r-1)}
\]</span></p>
</div>
<div id="tukey" class="section level3 hasAnchor">
<h3>多重比較とそれに伴う統計的問題<a href="ANOVA.html#tukey" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ANOVAにおける帰無仮説の棄却は、少なくとも1つの群は全体と異なる平均値を持っているという結論につながる。しかし、どれが異なる値を持つのかがわからないため、それを特定化するために多重比較と呼ばれる分析を行う。この多重比較には統計的問題が伴うと言われている。本節では多重比較に伴う統計的問題について考える。</p>
<p>多重比較に伴う問題は、第一種の誤り（帰無仮説が正しいときに帰無仮説を棄却する誤り）を起こす確率（有意水準）に着目し議論される。ANOVAにおける帰無仮説は以下のとおりである。
<span class="math display">\[
H_0:~ \mu_1=\mu_2=...=\mu_J
\]</span>
この帰無仮説を有意水準5%を設定し、 (8) 式の統計量を用いて検定した場合の<span class="math inline">\(H_0\)</span>に関する有意水準はもちろん5%になる。しかしながら、各グループごとの対となる検定を5%水準で行った場合、<span class="math inline">\(H_0:~ \mu_1=\mu_2=...=\mu_J\)</span>に対する有意水準は5%よりも大きくなってしまうと言われている。</p>
<p>この問題では、先述の<span class="math inline">\(H_0\)</span>に基づき、分散分析が捉えている全体としての第一種の誤りと多重比較で捉えている個別の第一種の誤りという構造を把握する必要がある。言い換えると、多重比較により複数の検定を繰り返し行う場合、その複数の検定を「検定のセット」と考え、セット全体での第一種の誤りについて考えるということになる。</p>
<p>この統計的問題についてより明確に説明するために、1要因3グループの分散分析という具体例を考える。この時、分散分析としての全体の帰無仮説は<span class="math inline">\(H_0:~ \mu_1=\mu_2=\mu_3\)</span>となる。ここで対となる2群環の平均の差の検定を行うと、<span class="math inline">\({}_3C_2=3\)</span> 通りのt検定を行うことになる。例えば、グループ1対グループ2の検定においては <span class="math inline">\(H_0^1:~\mu_1=\mu_2\)</span> という帰無仮説を採用して検定を行うことになる。これら各対の検定における帰無仮説が棄却されれば、分散分析全体として捉えていた帰無仮説（<span class="math inline">\(H_0:~ \mu_1=\mu_2=\mu_3\)</span>）も当然棄却されることになる。そのため、各対に関する帰無仮説が少なくともひとつ棄却されることで、全体としての帰無仮説が棄却されるという構造を捉える必要が出てくる。この構造が、第一種の誤りについての問題につながる。</p>
<p>各対に関する帰無仮説に対して第一種の誤りが起こる確率は、「ひとつ目の対の検定において誤りが起きる、またはふたつ目の対の検定において誤りが起きる、またはみっつ目の対の検定において誤りが起きる」という事象の確率を捉えることになる。仮に各対の検定において有意水準5%を設定した場合、3回に1回以上第一種の誤りを起こす確率（全体としての有意水準）は、それぞれの検定において第一種の誤りを犯すという事象が互いに独立だと仮定すると、以下の通り0.05よりも多くなる。
<span class="math display">\[
1-P(\text{3回中1回も第一種の誤りを犯さない})=1-(0.95)^3\approx 0.143
\]</span></p>
<p>そのため、分散分析に対応する複数の検定を繰り返し行う場合には、複数の検定を検定のセットと捉え、セット全体での第1種の誤りを犯す確率が事前に設定した有意水準（例：0.05等）以下に抑えられるような方法が求められる。この問題に対応した方法が多重比較法であり、代表的な例としてTukeyの多重比較法がある (Tukey’sのPairwise法については例えば南風原（2010)を参照してほしい)。</p>
</div>
<div id="ANOVAwithR" class="section level3 hasAnchor">
<h3>Rによる分散分析の実行<a href="ANOVA.html#ANOVAwithR" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Rで分散分析を実行すること自体は難しくない。ここでは、<a href="#statex"><strong>??</strong></a> 節で用いた <code>reshape2</code> データを用いて、以下の通りチップ額が曜日によって異なるか否かを分析する。ANOVAの実行においては<code>aov()</code>関数によって分析するモデルとデータを指定し、<code>anova()</code> によって分析結果を出力する（<code>summary()</code> を用いることも可能である）。なお、上記のデータサマリーより、<code>day</code> という要因には四水準 (levels) 含まれていることがうかがえる。</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="ANOVA.html#cb151-1" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb151-2"><a href="ANOVA.html#cb151-2" tabindex="-1"></a></span>
<span id="cb151-3"><a href="ANOVA.html#cb151-3" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">aov</span>(tip <span class="sc">~</span> day, <span class="at">data =</span> tips)</span>
<span id="cb151-4"><a href="ANOVA.html#cb151-4" tabindex="-1"></a><span class="fu">anova</span>(s)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: tip
##            Df Sum Sq Mean Sq F value Pr(&gt;F)
## day         3   9.53  3.1753  1.6724 0.1736
## Residuals 240 455.69  1.8987</code></pre>
<p>分析結果における <code>Sum Sq</code> は、水準間変動和（または、平方和）と呼ばれ、特定要因の水準間によって説明される観測値の変動を表している。 <code>Mean Sq</code> は平均平方と呼ばれ、Sum SqをDF(自由度)で割ったものである。<code>F value</code> は F値という検定統計量の実現値であり、<code>Pr(&gt;F)</code> は本検定の p値を表している。また、<code>Residuals</code> の行で示されているのは、残差平方和と呼ばれ、郡内変動、つまり同グループ（水準）内での値のばらつきの程度を表している。</p>
<p>本結果の場合、曜日間でのチップ額についての差についての推定値（<code>F value</code>）は<code>1.6724</code> であった。そして、これが統計的に有意なのかについて検討するためにp値を参照する。このときp値は <code>0.1736</code> であり、帰無仮説が正しいと仮定したときに，手元のデータから計算した検定統計量以上に極端な値をとる確率は17％以上あるといえる。このことから、有意水準 5% で仮説検定を行っても帰無仮説を棄却できないと解釈でき、曜日による統計的に有意な差があるとは言えない。ANOVA実行している検定では、「すべての水準間で平均値は同じ」という帰無仮説を検定しており、仮に帰無仮説が棄却された場合、「少なくとも一つの水準では値が異なる」という対立仮説を支持する。そのため、ANOVAにおける帰無仮説の棄却は、少なくとも1つの群は全体と異なる平均値を持っているという結論につながる。今回の結果では、このような帰無仮説も棄却するに至らなかったということである。</p>
<p>もし仮にANOVAにおける帰無仮説が棄却されたとしても、それだけでは具体的にどの水準間に差があるのかはわからない。そこで、ANOVAを用いた研究では事後分析として、多重比較と呼ばれる分析を行うことが多い。しかし、この多重比較には統計的な問題が伴うと言われている（詳細は<a href="ANOVA.html#tukey"><strong>??</strong></a>節参照）。その問題に対応した手法として広く用いられているのが、Tukeyのpair-wise 比較である。Rではこの分析を、<code>TukeyHSD()</code> という関数で実行できる。具体的には、<code>aov()</code> でストアしたANOVAの分析結果を用いて以下のように実施する。また、<code>plot()</code>を用いて、pair-wise比較の結果を95%信頼区間とともに図示化することもできる。</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="ANOVA.html#cb153-1" tabindex="-1"></a>tukey_result <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(s)</span>
<span id="cb153-2"><a href="ANOVA.html#cb153-2" tabindex="-1"></a>tukey_result</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = tip ~ day, data = tips)
## 
## $day
##                 diff        lwr       upr     p adj
## Sat-Fri   0.25836661 -0.6443694 1.1611026 0.8806455
## Sun-Fri   0.52039474 -0.3939763 1.4347658 0.4558054
## Thur-Fri  0.03671477 -0.8980753 0.9715049 0.9996235
## Sun-Sat   0.26202813 -0.2976929 0.8217492 0.6203822
## Thur-Sat -0.22165184 -0.8141430 0.3708394 0.7678581
## Thur-Sun -0.48367997 -1.0937520 0.1263921 0.1724212</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="ANOVA.html#cb155-1" tabindex="-1"></a><span class="fu">plot</span>(tukey_result)</span></code></pre></div>
<p><img src="03-stat_files/figure-html/tukeys-1.png" width="672" /></p>
<p>分析結果における <code>diff</code> 列は平均値の差を表している。 <code>lwer</code> と <code>upr</code> は信頼区間の下限と上限を表しており、一番右の列はp値を示している。分析の結果、P-valueが10%水準よりも低い結果がないため、どのペアに関する検定でも有意な差は確認できなかった。したがって、分析結果は必ずしもチップ額が曜日によって変化するとは言えないことを示した。この結果は、アメリカにおけるチップ額が会計額に対する割合や提供されたサービス品質によって決まるという慣習から考えると妥当な結果である。しかしながら、前節で注意した通り、このような統計的に非有意な結果をもって「曜日はチップ額に影響を与えない」と結論づけるのは不適切である。</p>
<p>なお、今回の分析においてはANOVAもTukeyのpair-wise比較も有意な結論を得ることができなかったという点で、両者の結果に一貫性があった。しかしながら、ANOVAでは有意だが、Tukeyの分析ではどの組み合わせも有意ではないという一見整合でない結果を得ることもある。その場合には、慣習としてTukeyの多重比較結果を優先して解釈を提示することが多い。しかしながら、研究者が自身の実施した検定の「意味」を理解し、解釈や議論を提示することも重要である。例えば、ANOVAとTukeyでは用いている帰無仮説が異なるため、異なる比較対象を用いた検定を実施している。そのため、自身が実行した分析がどのような帰無仮説を採用しており、何と何の比較を行っているのかを正確に把握し、実施した検定の意味に適した解釈や議論を展開する事が重要になる。</p>
<p>本章では、基礎的な統計学の復習として、主に区間推定と統計的仮説検定について説明した。区間推定では、主に信頼区間の計算に着目し、信頼区間の意味についてきちんと理解、解釈することの重要性を強調した。また、統計的仮説検定では、母平均の検定を起点とし統計的検定の基礎的な構造と考え方について説明した。検定においては、母集団の統計的特徴に関する予測である帰無仮説と対立仮説を設計することが重要である。また、グループ間の差異に着目した検定を行う場合には、関心のある未知パラメータについての差や比に着目し検定統計量を作成する事が多いが、基本的な統計的検定の考え方と手順は変わらないという点についても説明した。</p>
</div>
<div id="ANOVAandReg" class="section level3 hasAnchor">
<h3>回帰分析と分散分析の関係<a href="ANOVA.html#ANOVAandReg" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>分散分析は回帰分析の特別な場合（回帰分析における独立変数をダミー変数とした場合）に対応する。ダミー変数とは以下の様な2値変数である。
<span class="math display">\[
x_i=\left\{
\begin{array}{l}
1~~~\text{if 被験者iは1群に属する}\\
0~~~\text{otherwise}
\end{array}
\right.
\]</span>
そのため、2標本問題は、<span class="math inline">\(y=\beta_0 +\beta_1x+e,\)</span> において、以下を検定することと等しい。
<span class="math display">\[
\begin{array}{l}
H_0:~ \beta_1=0\\
H_1:~ \beta_1\not=0
\end{array}
\]</span></p>
<p>また、ダミー変数の効果は以下のように定数項（切片）の違いとして表すことができる。
<span class="math display">\[
E(y|x=1)=\beta_0+\beta_1
\]</span>
<span class="math display">\[
E(y|x=0)=\beta_0
\]</span></p>
<p>二元配置に関しては、以下のように、交差項 (interaction term) を含む回帰分析として分析を行えば良い。
<span class="math display">\[
y=\beta_0 +\beta_1x+\beta_2z+\beta_3(x\times z)+e,
\]</span></p>
<p>この場合、xがyに与える影響は以下のように表される。
<span class="math display">\[
\frac{\partial y}{\partial x}=\beta_1+\beta_3z
\]</span>
一方で、zがyに与える影響は以下のように表される。
<span class="math display">\[
\frac{\partial y}{\partial z}=\beta_2+\beta_3x
\]</span>
そのため、xとzがyへ与える影響は互いがそれぞれに依存しており、<span class="math inline">\(\beta_3\)</span>によってそれぞれの影響に対する調整効果が表されている。</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="meancomparison.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="pwr.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-stat.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "scroll_highlight": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
